package:
  name: cryosparc-tools
  version: 5.0.0
source:
  url: https://files.pythonhosted.org/packages/a1/84/8d1a4c4a66b0f1a534d8403015e07dfb616fb4d2ce306b9078acc9c0955a/cryosparc_tools-5.0.0.tar.gz
  sha256: 84bb5cf706776556be92ec3166b61a53a426ef5eccddccabd5bf668314cb9fc0
build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv"
requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python 3.12.*
    - pip
    - setuptools
    - cython
  run:
    - python >=3.12,<3.13
    - numpy >=1.26,<3
    - httpx >=0.25,<1
    - pydantic >=2.8,<3
    - typing-extensions >=4
test:
  imports:
    - cryosparc.tools
    - cryosparc.dataset
  commands:
    - python -c "from cryosparc.dataset import Dataset; assert len(Dataset()) == 0"
about:
  home: https://tools.cryosparc.com
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Toolkit for interfacing with CryoSPARC
